### ISSUE TITLE
Spine not responsive on Nexus 7 tablet

### ISSUE THREAD

**Issue by MichelleFelt** [washingtonstateuniversity/ucomm.wsu.edu#15]
Spine not responsive on Nexus 7 tablet, android version 4.4.2. in the Chrome browser.

![](http://i.imgur.com/LLxYKyU.jpg)

![](http://i.imgur.com/CjiMhRk.jpg)

**Comment by jeremyfelt** [comment]
This was apparently fixed in https://github.com/washingtonstateuniversity/WSU-spine/commit/54107be9939c7a475a68e5f1299950b6d1fe8939
