### ISSUE TITLE
Map size

### ISSUE THREAD

**Issue by MichelleFelt** [washingtonstateuniversity/ucomm.wsu.edu#16]
http://ucomm.wsu.edu/contact/

Received note "the map is too small and doesn't work correctly". It seems to work correctly but I think it's an issue of the info pin taking up so much space in a small map. 

Any ideas? Make the map a little larger or can we default so the pin info isn't present?

![screen shot 2014-07-31 at 1 52 04 pm](https://cloud.githubusercontent.com/assets/6111174/3771383/9f8f14f6-18f4-11e4-8382-23e5cbbefff4.png)

**Comment by jeremyfelt** [comment]
Closing this out - I removed the map link from the contact page because it's completely broken. :)
