### ISSUE TITLE
Front page responsiveness issue with text

### ISSUE THREAD

**Issue by MichelleFelt** [washingtonstateuniversity/ucomm.wsu.edu#17]
On front page when screen is resized in (Chrome - MacBook Air or Firefox - MacBook Pro) text overlaps video still

![unknown](https://cloud.githubusercontent.com/assets/6111174/3786229/b0de0ea4-19d2-11e4-9197-8e5fda8939cb.png)

**Comment by jeremyfelt** [comment]
This seems to no longer be a thing.
